name: "Full Web Server"
version: "1.0.4"
slug: "full_web_server"
description: "Server web NGINX complet (full option) care servește automat fișierele din folderul /share/webserver. Acum cu suport Ingress!"
arch:
  - amd64
  - aarch64
  - armhf
  - armv7
init: false
map:
  - share:rw
ingress: true
ingress_port: 80
panel_icon: mdi:web
panel_title: "Web Server"
options:
  autoindex: true
schema:
  autoindex: bool
ports:
  80/tcp: 8080
ports_description:
  80/tcp: "Portul extern prin care accesezi serverul web (default 8080)"
url: "https://github.com/vlad2939/home-assistant-addons"
