user root;
worker_processes  1;
pid /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    tcp_nopush      on;
    tcp_nodelay     on;
    keepalive_timeout  65;
    types_hash_max_size 2048;

    # Gzip Settings
    gzip on;
    gzip_disable "msie6";
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    server {
        # Containerul ascultă pe 80; HA mappeză 8080 la 80
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        # Rădăcina folderului de unde sunt servite fișierele
        root   /share/webserver;
        
        # Ce fișier afișează implicit
        index  index.html index.htm index.php;

        # Evită redirecturile absolute care scot utilizatorul din Ingress (Home Assistant)
        absolute_redirect off;

        location / {
            # Activează auto-listarea de foldere dacă nu există index.html
            autoindex on;
            autoindex_exact_size off;
            autoindex_localtime on;
            
            try_files $uri $uri/ =404;
        }

        # Pagini de eroare standardizate
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /var/lib/nginx/html;
        }

        # Securitate de bază: Ascunde fișierele de sistem/ascunse
        location ~ /\.ht {
            deny all;
        }
    }
}
