server {
    listen 80;
    server_name _;
    
    # Locația reală din Home Assistant montată direct ca Root Document
    root /share/wordpress;
    index index.php index.html index.htm;

    # Setare Limită de Upload Fișiere și Teme în Nginx (256 MB)
    client_max_body_size 256M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        # Conectare FastCGI pe localhost port 9000
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
    
    # Protecție pentru fișiere sensibile
    location ~ /\.ht {
        deny all;
    }
}
